### ISSUE TITLE
Is it possible to set the lifetime of access/id token?

### ISSUE THREAD

**Issue by Rookian** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#1]
I would like to test token expiration and silent refresh. 

Is it possible to set the lifetime of access/id token?

**Comment by jeroenheijmans** [comment]
The lifetime is determined by your server, and included in the signed part. I typically test this by spinning up my own Identity Server with a 30 sec timeout on the token.

I do think though that the expiration time is extracted and persisted seperately in your `OAuthStorage` of choice. So you could do something like this (untested):

```typescript
this.oAuthService.events
  .pipe(filter(e => ['token_received'].includes(e.type)))
  .subscribe(_ => {
    this.oAuthStorage.setItem('access_token_stored_at', yourValueHere);
    this.oAuthStorage.setItem('expires_at', yourValueHere);
  });
```

Same for the `id_token` storage items.

Easier however I think is to use [`timeoutFactor`](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#timeoutFactor) and set it to `0.05` or however small you need it. This way the refresh is initiated after 5% of the total token lifetime has passed, allowing for quicker testing.

Finally, for seperately testing if silent refreshes work am sich, you could also just call `this.oAuthService.silentRefresh()` which just triggers a silent refresh right away.

PS. To see what's going on, I suggest also doing this in debug mode:

```typescript
this.oAuthService.events.subscribe(e => (e instanceof OAuthErrorEvent) ? console.error(e) : console.warn(e));
```

Hope that helps.

**Comment by jeroenheijmans** [comment]
Woah, wait a second, I only just saw that this issue was posted on my sample repo, not on the library's repo :blush:

That means the:

- logging part is already in there (that final tip)
- the `timeoutfactor` already is somewhat lower, see [this file](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/master/src/app/auth-config.ts), but you can lower it even further
