### ISSUE TITLE
Silent refresh problem when using Google Chrome

### ISSUE THREAD

**Issue by jplette** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#10]
I found some weird behaviour in chrome. But I guess it is a problem with the angular-oauth2-oidc library.
It seems that the session is changed after the login, so the refreshing fails with "silent refresh failed after session changed"

Can you confirm this problem in chrome? In Edge and Firefox it works as expected.

**Comment by jeroenheijmans** [comment]
No, sorry, I cannot confirm. If I just serve up the current master branch locally, it works as expected. See here:

![no-repro-issue-3](https://user-images.githubusercontent.com/1590536/49176091-5db3e400-f34a-11e8-8a01-f1e151f83182.gif)

(Linked to [482 in the lib's repository](https://github.com/manfredsteyer/angular-oauth2-oidc/issues/482))

**Comment by jplette** [comment]
Ok, that's how it look in my Chrome:
Version 70.0.3538.110 (Offizieller Build) (64-Bit)

![silent_refresh2](https://user-images.githubusercontent.com/6105027/49177591-e8e2a900-f34d-11e8-80d6-d49cb3f638da.gif)

**Comment by jplette** [comment]
![image](https://user-images.githubusercontent.com/6105027/49178311-bafe6400-f34f-11e8-84cb-631693e7c761.png)

**Comment by jplette** [comment]
Sorry, I don't want to bother you. I've stumbled about your demo project, because I was interested in an implementation with an auth-guard. I know this is for sure a problem with the angular-oauth2-oidc lib... Thank you...

**Comment by jplette** [comment]
Thank you, for the hint in the right direction.
In my chrome settings I disallowed 3rd party cookies.

**Comment by gaalvarez** [comment]
In my case the error is caused by keycloak and chrome security configuration when the keycloak is deployed whitout tls/ssl.

For solve the problem I set the "SameSite by default cookies" to disabled using the next link in chrome: chrome://flags/#same-site-by-default-cookies. This link works in brave too.
