### ISSUE TITLE
Difference between this sample repository and the samples in the library's repository

### ISSUE THREAD

**Issue by git9999999** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#108]
Hi 

First, thank for providing a Sample Project :-)

I try to implement the angular-oauth2-oidc in my Project. I copied over the AuthService from this sample project. 

Now i studied the angular-oauth2-oidc documentation https://github.com/manfredsteyer/angular-oauth2-oidc#logging-in. I am under the Impression that i just have to call im my code "this.oauthService.initCodeFlow();" 

Or mybe this too:
this.oauthService.configure(authCodeFlowConfig);
this.oauthService.loadDiscoveryDocumentAndTryLogin();

In your Code, the AuthService the runInitialLoginSequence does quite some stuff. 

I am not sure what to do now? Take your code or try the use the documented way.

Please could you explain what does your code other than the original one.

Now i have seen that here is another Example within the SouceCode Repo of angular-oauth2-oidc, quickstart-demo. It does only this for initialisation:

```
 constructor(private oauthService: OAuthService) {
    this.oauthService.configure(authCodeFlowConfig);
    this.oauthService.loadDiscoveryDocumentAndLogin();

    //this.oauthService.setupAutomaticSilentRefresh();

    // Automatically load user profile
    this.oauthService.events
      .pipe(filter((e) => e.type === 'token_received'))
      .subscribe((_) => this.oauthService.loadUserProfile());
  }
```

Thanks 

Beste Regards 
G

**Comment by jeroenheijmans** [comment]
Glad the sample was of help!

I think the samples you mention have different aims. The sample in the library itself aims to provide the _minimal_ way to be able to use the library. My sample here tries to give a very opinionated and larger example. It shows _many_ of the available bells and whistles from the library, and reflects the way *I* would (and do) use the library in my production applications.

So:

- if you want to fine-tune your use case yourself: start from the library's samples and build from there, using documentation
- if you want to quick start from existing boilerplate: use any or all of the code in this sample implementation

Either option is valid. What's best depends on your style and situation.

Hope that helps!
