### ISSUE TITLE
isAuthenticated observable is false when localStorage is used

### ISSUE THREAD

**Issue by jwoyame** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#117]
Thank you for this excellent sample.

The `isAuthenticated` observable produces a correct value when logging in or after a silent refresh. However, it doesn't seem there is any event to update the value when the application first loads and there is already a valid access token available in localStorage.

Current code:

```typescript
    this.oauthService.events
      .subscribe(_ => {
        this.isAuthenticatedSubject$.next(this.oauthService.hasValidAccessToken());
      });
```

Proposed fix:

```typescript
    this.oauthService.events
      .subscribe(_ => {
        this.isAuthenticatedSubject$.next(this.oauthService.hasValidAccessToken());
      });
    // see if already logged in
    this.isAuthenticatedSubject$.next(this.oauthService.hasValidAccessToken());
```

**Comment by jeroenheijmans** [comment]
Interesting! Thanks for your suggestion. At first glance this seems like a nice improvement! Will try to look at it somewhere during the week, a bit busy at work at the moment.

**Comment by jwoyame** [comment]
I just want to clarify exactly what caused my issue.

It sometimes works fine and sometimes doesn't detect that the user is already authenticated.

When visiting the page while a valid access token is already stored, sometimes `isAuthenticated` is correctly true, and other times it was incorrectly false. It turned out that it was incorrectly false only right after I log in.

I traced this to the fact that if the `timeoutFactor` on the access token is exceeded, then the `setupAccessTokenTimer` function would trigger an event, and this would cause this line to run in the sample:

```typescript
this.isAuthenticatedSubject$.next(this.oauthService.hasValidAccessToken());
``` 

However, if the token timer is not firing, there are no events at all that would trigger this code to run. The fix was to make sure it always runs initially when the app is loaded.

**Comment by jeroenheijmans** [comment]
Thx for the fix! I've added some tests and merged your PR. ♥🙏
