### ISSUE TITLE
Question - Howto redirect to login page directly

### ISSUE THREAD

**Issue by Jolynice** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#127]
Hello ,

It´s just a question and not an issue.

I love to much this example , and I planned to use it, but I would like to ask help, to know what to change to directly go the login page if the user is not logged.

Best regards,
Jolynice

**Comment by jeroenheijmans** [comment]
Heya! Glad it helped.

Just slap this on all routes you want the user to be forcibly logged into:

```
canActivate: [AuthGuardWithForcedLogin]
```

You can see it [here in action](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/ec1a0c247aea227c92f0a91e5fed6fe866fbabbe/src/app/feature-extras/extras.module.ts#L17), if you open that page's url directly it will make the user login automatically.

Alternatively, if there's absolutely zero pages (not even a help page or whatever) that can be viewed without logging in, you can also hook into things here:

https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/ec1a0c247aea227c92f0a91e5fed6fe866fbabbe/src/app/core/auth.service.ts#L133-L136

Cheer!
