### ISSUE TITLE
Preload loadDiscoveryDocument using APP_INITIALIZER 

### ISSUE THREAD

**Issue by alecrt** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#13]
Hi @jeroenheijmans,

what do you think about pre-loading the discovery document in the angular initialization stage?

Thank you, 
Alessandro

**Comment by alecrt** [comment]
Ah, great example!

**Comment by jeroenheijmans** [comment]
@alecrt Could you elaborate a bit?

I mean, you could certainly do so if it makes sense for your application. But the main use case for my repository is so people can try it with their _own_ Identity Server. So auto-discovery makes the most sense to me.

Let me know (e.g. with pseudo-code) what you would like to see changed.

**Comment by jeroenheijmans** [comment]
Wait, re-reading the title more carefully, I now see what you mean. You would want the app initialization to wait for the disco document to be loaded, before continuing. I thought you were suggesting hard-coding a config grabbed from an openid-configuration endpoint

What would we gain from moving the loading to the app initializer? And is it easily possible to have _asynchronous_ initialization logic?

**Comment by jeroenheijmans** [comment]
Related:

- [Issue to improve docs around APP_INITIALIZER use with the oauth library](https://github.com/manfredsteyer/angular-oauth2-oidc/issues/607)
- [Thread with some info on how to do this, currently](https://github.com/manfredsteyer/angular-oauth2-oidc/issues/606)

I think I prefer to keep my example simple, and just `provide` the `AuthConfig`, and refer to the new docs if people need async app initialization to load configuration.
