### ISSUE TITLE
Upgrade Sample to Angular 18

### ISSUE THREAD

**Issue by jeroenheijmans** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#157]
Angular 18 was released in May 2024, so it's time to upgrade this sample. Most likely the `angular-oauth2-oidc` library version will work just fine with the latest Angular version, and we can just upgrade. 

See also: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1413

**Comment by claudia9** [comment]
Hi @jeroenheijmans and @manfredsteyer
Is there any plan to upgrade this library to support Angular 18?
We are blocked in our project due to this

**Comment by jeroenheijmans** [comment]
Good question @claudia9! Be ware though, you've posted your question on this "satellite" repository, which is just a _sample_ implementation with the library. I don't think your project would be blocked by my sample being a bit out of date. You may want to chip in at [the relevant issue for the library itself](https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1413)?

Having said that, for most previous Angular versions we could just upgrade Angular itself while keeping the existing version of the angular-oauth2-oidc library in use. I wouldn't be surprised if that's the case with verison 18 as well. Have you tried upgrading yet and ran into actual issues? Might be good to add those to the discussion in linked issue.

Not sure when I myself would have time to update my sample repository here. I would welcome a PR from the community, just be sure to keep it very focused on just that upgrade, for inspiration check [the Angular 17 upgrade changes](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/pull/150/files).

**Comment by jeroenheijmans** [comment]
Just confirmed that v17 of the library works just fine with latest Angular, as far as my sample is concerned. You can check the latest main version to see it in action. I recommend trying it in your own projects too if you need it.

(It can still be useful to have the library get an upgraded version of the package, if only for clarity. But that's outside the scope of my sample repository.)
