### ISSUE TITLE
Hash location strategy for Angular 14.x redirect url lost

### ISSUE THREAD

**Issue by sajita123** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#158]
I am facing one problem with redirect url for hash location strategy routing.

Every time when I am trying to navigate directly to some page from the application, if I'd token expires or not logged in then after authentication it navigate to dashboard irrespective of previous state. After going through the documentation if I am trying to add initialNavigation false then angular error. So please guide me to the particular step needs to be written in the code to redirecturl handling. Any sample code also I couldn't find. 

Used Angular version - 14.x
Library version- 14.x

**Comment by jeroenheijmans** [comment]
Dear @sajita123, ooh, that sounds like an intricate bug/situation.

Note that you've posted on my `sample-angular-oauth2-oidc-with-auth-guards` repository's issues list. I'm just one person providing a sample / starter implementation. I'm happy to tackle any issues to improve or change the sample itself, but am unable to provide support for individual implementations.

There are some alternatives you can try. The way you've written your post it sounds like you need a consultant, friend,colleague, or AI tool to pair program with you on that specific issue. There's too little to go on in your text to help you as a community member. So my first suggestion would be to find/hire one of those. - If you want community support I recommend trying online forums for this type of question (or if you think this is a bug in the code or documentation of the library you could open an issue on the [library repository](https://github.com/manfredsteyer/angular-oauth2-oidc)), but in all those cases you'd need to provide enough information and code for the other to go on.

Hope this all makes sense, and hoping for your understanding in closing this issue for this particular repository. Good luck!
