### ISSUE TITLE
modify behavior of default interceptor

### ISSUE THREAD

**Issue by nouaim** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#159]
Hello, can anyone please suggest how can we modify the behavior of default interceptor of the library, or create another interceptor that work in parallel with the default one?

I would like to send a session id instead of the bearer token since my backend api requires that

**Comment by jeroenheijmans** [comment]
Hi @nouaim! I think you're looking for [the library's issue list](https://github.com/manfredsteyer/angular-oauth2-oidc/issues) instead; you're currently posting on the list of issues for my personal sample implementation. I am but one person and cannot unfortunately support individual requests or generic library questions, hope that makes sense?

PS. Perhaps [the interceptor documentation](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/additional-documentation/working-with-httpinterceptors.html) is already what you're looking for?
