### ISSUE TITLE
Signing you in component instead of Fallback

### ISSUE THREAD

**Issue by coder925** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#25]
When being redirected from the identity server back to the app, the _FallbackComponent_ is briefly displayed during the signin process:
![fallback-component](https://user-images.githubusercontent.com/24881789/63093371-2bdcbf00-bf65-11e9-9ee6-fda5680ee524.gif)

Usually in apps, the _FallbackComponent_ contains text like: “_404 – Could not find the requested page_” which you don’t want to display during the signin is processing.

What do you think about having a specific route for path `index.html#id_token=…` to a SigninInprogressComponent that will display “_Signing you in… Please wait._”?

**Comment by jeroenheijmans** [comment]
Ah yes, thx for the detailed issue.

I certainly agree that _something_ should be improved here. Not sure if a route for that path is best... in my production app we just make the "Authenticating...." overlay you see in your screenshot not-transparent. I only made it semi-opaque in my sampleso you can see what's going on in the background.

In short, if you run into this in your application: consider making the "Loading/Authenticating" overlay fully opaque, and you're good to go.

**Comment by coder925** [comment]
Thanks! Yes, that is probably the easiest way to go.

As it turns out, I didn’t have enough skills to do a full match of the redirect URL including hashes. The only hacky option that I actually got working was adding:
`{ path: 'index.html', component: SigninInprogressComponent },`

As a last option, I noticed that I could also add a guard to the _FallbackComponent_ even if that is probably not want you want in general.

**Comment by jeroenheijmans** [comment]
Thx again for reporting a detailed issue back when! Looking back, I think I will leave the choice of how to do this up to individual app developers. 

The basic option of making the overlay fully opaque is simple and works for most of the cases. In this app I explicitly leave it semi-opaque, so you can see what's going on in the background. That seems more useful for a demo app anyways.
