### ISSUE TITLE
Hash fragments with session_state, sate, id_token etc not getting set in session storage

### ISSUE THREAD

**Issue by erabhishek211** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#26]
```
UrlHelperService.prototype.getHashFragmentParams = 
    function (customHashFragment) {
        /** @type {?} */
        **var hash = customHashFragment || window.location.hash;**
        hash = decodeURIComponent(hash);
        if (hash.indexOf('#') !== 0) {
            return {};
        }
        /** @type {?} */
        var questionMarkPosition = hash.indexOf('?');
        if (questionMarkPosition > -1) {
            hash = hash.substr(questionMarkPosition + 1);
        }
        else {
            hash = hash.substr(1);
        }
        return this.parseQueryString(hash);
    };
```

I want to set some value to the `customHashFragment` instead of taking it from `window.location.hash`. Is there a way to configure this?

**Comment by jeroenheijmans** [comment]
Hi! I think you may have the wrong idea, you've opened an issue for my repository with a sample about using the oauth library. I'm sorry, but I don't have time for generic and mostly unrelated support questions. Please try a forum or Q&A site where a larger community can take the load of asking, or get a hold of a peer or colleague or consultant. Good luck!
