### ISSUE TITLE
Should this be initLoginFlow instead?

### ISSUE THREAD

**Issue by maxisam** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#32]
https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/c73b0f2feaf608e312b6faa67203f340de80c2ed/src/app/core/auth.service.ts#L179

**Comment by jeroenheijmans** [comment]
Yes, that seems to be correct. Will double check later and merge, thx for this!

**Comment by jeroenheijmans** [comment]
Thanks @maxisam, worked like a charm!
