### ISSUE TITLE
still using initImplicitFlow() on should-login cp

### ISSUE THREAD

**Issue by kemmis** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#38]
https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/master/src/app/should-login.component.ts#L14

Since this project was updated to code flow, shouldn't this line call `initCodeFlow()` or `initLoginFlow()` instead of `initImplicitFlow()`?

**Comment by jeroenheijmans** [comment]
Yes, seems you're right! Or even [`initLoginFlow`](https://github.com/manfredsteyer/angular-oauth2-oidc/blob/84d95a7f31783a4a3f81525d94f3bc05d1f6ff86/projects/lib/src/oauth-service.ts#L2491-L2497) so it can be the same thing in two branches.
