### ISSUE TITLE
Login when user opens the page

### ISSUE THREAD

**Issue by mrkannan3** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#39]
Hi,

I am trying to change this code to login automatically when user browse the home page. I updated the app menu component file to call the login method in the constructor but its keep looping. Could you please help me to figure out the issue? Thanks

**Comment by jeroenheijmans** [comment]
Enabling [the commented out feature](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/4f0df3f537282ba3175435949a92ed72a7a99392/src/app/core/auth.service.ts#L131-L132) _should_ do the trick. 

Alternatively, you can slap [the forced login guard](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/master/src/app/core/auth-guard-with-forced-login.service.ts) on all routes in your app, including the home page. This has an advantage, that you could leave one or two pages (FAQ, 404, etc) unprotected if you want.

**Comment by jeroenheijmans** [comment]
Hope those pointers help! If you need lots more help thinking through your app design, another forum, or a colleague/friend, might be more readily available. Good luck!

**Comment by mrkannan3** [comment]
Thanks for the pointer. I actually implemented by doing this.

https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/projects/sample/src/app/home/home.component.ts#L28

 this.oauthService.loadDiscoveryDocumentAndTryLogin().then(_ => {
            if (!this.oauthService.hasValidIdToken() || !this.oauthService.hasValidAccessToken()) {
              this.oauthService.initImplicitFlow('some-state');
            }
        });

I will check out your pointer as well.
