### ISSUE TITLE
This is great example but lack proper documentation.

### ISSUE THREAD

**Issue by ak274** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#48]
Thanks for providing this example.

But i feel it really lag because of no documentation or explanation of service and auth-gaurds, you should provide documentation for it.

**Comment by jeroenheijmans** [comment]
Thanks for your kind words, glad it helped!

I understand and appreciate the request for docs, but I think I might not add them, they are intentionally omitted. The whole intention of this sample is to document the library through _code_, not prose. [The README](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/master/README.md) is likely all I'd ever have as far as docs go.

Hope you can understand!

PS. Note that there are [official library docs](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/) that document how the library works.
