### ISSUE TITLE
Enable and document running with TLS

### ISSUE THREAD

**Issue by jeroenheijmans** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#62]
It would be nice if this sample was even _more_ exemplary and allowed serving with _https_ locally. To fix this issue, I'm not 100% sure what needs to be done, but in the end:

1. The `README.md` should be updated with a small section or note on how to use TLS
2. The `package.json` scripts should be updated to support running both with http and with https
3. It should work on both Windows and *nix OSes

I'm not sure what to do about the e2e tests though, and open to suggestions. It might be nice if they run with https as well, then again they should also reflect what you'd get after clone-and-run (which might remain http?). Open to suggestions from whomever picks up this issue.

PS. There's [a `sample-angular-oauth2-oidc-with-auth-guards` channel in the contributing.today Discord](https://discord.gg/rF8GBrP) where I'll be if anyone has hacktoberfest-related questions!

**Comment by gagandeepp** [comment]
Assign this to me

**Comment by jeroenheijmans** [comment]
Will do! Thx for giving it a go!

**Comment by gagandeepp** [comment]
@jeroenheijmans  any update on this?

**Comment by jeroenheijmans** [comment]
Aye, updated at the PR, see: https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/pull/70#issuecomment-718725173

**Comment by jeroenheijmans** [comment]
Merged #70
