### ISSUE TITLE
Login does not work on Chrome for IOS

### ISSUE THREAD

**Issue by Yanal-Yves** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#64]
STR:
1) With Chrome for IOS on IPAD or IPhone, go to http://sample-angular-oauth2-oidc-with-auth-guards.s3-website.eu-west-3.amazonaws.com where I have deployed this repository code with minor changes to allow deployment to AWS S3.
2) Hit "login" button
3) Enter credentials (bob/bob) and be focused on the behaviour

Results:
1) IsAuthenticated, HasValidToken, IsDoneLoading and CanActivateProtectedRoutes are true for a couple of seconds then are switched back to false.
2) IdentityClaims, AccessToken and IdToken are showing up for a couple of seconds then are switched back to null.

Expected results:
I should remain logged in.

Trace: https://gist.github.com/Yanal-Yves/0b7a30e49417d297e0c1276b4210d267
To get this trace, I built Chromium on a Mac book pro (With Xcode 12.0.1 installed) and ran it on an IPhone simulator. To do so I followed [this instructions](https://chromium.googlesource.com/chromium/src/+/master/docs/ios/build_instructions.md) and more precisely I:
1. Built Chromium for IOS
1.1 `mkdir chromium && cd chromium`
1.2 `git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git`
1.3 `export PATH="$PATH:~/chromium/depot_tools"`
1.4 `mkdir chromium && cd chromium`
1.5 ` fetch --no-history ios`
1.6 `cd src`
1.7 `ios/build/tools/setup-gn.py`
1.8 `autoninja -C out/Debug-iphonesimulator gn_all`
1.9 `out/Debug-iphonesimulator/iossim out/Debug-iphonesimulator/Chromium.app`
2. I opened the simulator and the built Chromium for IOS
3. I followed the STR described above in this issue.

**Comment by jeroenheijmans** [comment]
I can reproduce this behavior by opening up the link you provided in Chrome Incognito with the "Block 3rd party cookies" checkbox ticked. So I presume (I haven't followed your exact repro yet though) that you're running into #40 (which links to [a blogpost I wrote](https://infi.nl/nieuws/spa-necromancy/) detailing the issue and potential workarounds.

(Basically browsers are starting to block cookies from Identity Servers that are on another domain than the SPA.)

Would you agree with my assumption that this is also the case here?

**Comment by Yanal-Yves** [comment]
@jeroenheijmans, thank you for your answer.

I have also reproduced the issue with Chrome Incognito with the "Block 3rd party cookies" checkbox ticked. 

When I compare the console output, it look similar from what I can see in Chrome for IOS. So I agree with your assumption that this issue is due to the new browser behavior where cookie in the iframe are not sent to the ids server.

**Comment by Yanal-Yves** [comment]
So it looks like this issue is a dup of #40. So I am closing it

**Comment by jeroenheijmans** [comment]
Thanks for the quick feedback! Hopefully that issue and my blogpost will give enough help to figure out a way forward. Good luck!
