### ISSUE TITLE
Where can i use "stopAutomaticRefresh" in this template?

### ISSUE THREAD

**Issue by alissonmelonascimento** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#65]
Where can i use "stopAutomaticRefresh" in this template?

**Comment by jeroenheijmans** [comment]
Hmm, not sure if I follow the question entirely... You can call that anywhere you see fit for your use case. So it depends on what you're trying to achieve?

If you mean to ask whether it's available for testing purposes somewhere in this sample: it is not, at least not currently. It might be a bit more of an advanced feature so not sure if adding it to this sample is worth the extra complexity...

Does that answer your question?

**Comment by jeroenheijmans** [comment]
Let us know if you have further questions!
