### ISSUE TITLE
Silent refresh problem

### ISSUE THREAD

**Issue by nadworny** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#78]
Great sample app, thanks!

I'm trying to integrate the same logic in my app but something with silent-refresh doesn't work as expected. Basically, I've copy-pasted the auth-service, config, and initialized it in my app. I've also created a new component for the silent-refresh using `ng generate component silent-refresh` and replaced the `silent-refresh.component.html` with your `silent-refresh.html`. So everything seems to work until the token invocation is triggered by the silent-refresh - there I get 400 and afterwards error that the redirect_uri is wrong although it's configured properly in Okta.

**Request**
```
curl 'https://dev-522845.oktapreview.com/oauth2/v1/token' \
  -H 'referer: http://localhost:4200/' \
  --data-raw 'grant_type=authorization_code&code=xxx&redirect_uri=http://localhost:4200/ui&code_verifier=xxx&client_id=xxx' \
```
**Error**
```
{"error":"invalid_grant","error_description":"The 'redirect_uri' does not match the redirection URI used in the authorization request."}
```

![image](https://user-images.githubusercontent.com/1425919/113911240-0b1c4980-97da-11eb-961a-b7a48f47fc6d.png)

I know it's very vague but maybe you have an idea what I might be doing wrong?

**Comment by jeroenheijmans** [comment]
Nice to hear the sample was helpful!

Not sure what to tell you though, your server's configuration does _not_ like the redirect uri that's being sent along. I recommend checking with Okta support. One other thing you could do is clone my entire sample repository and just reconfigure it to talk to your Server. I mean: the sample works with IdentityServer4's demo server, so if you point it to your IDS it should just start working.... but I suspect it'll tell you that the redirect uri is not acceptable.

Good luck!

**Comment by jeroenheijmans** [comment]
PS. I will unfortunately close the issue, as I am just one person and don't have room for extensive support on individual implementations. Hope you understand. (Feel free to leave a comment if you found the solution though, as it might help others.)

**Comment by nadworny** [comment]
Not sure what I changed but it started working 🤣  

silent-refresh, unfortunately, doesn't seem to work with Okta. It seems this issue is back again: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/927. I think Okta doesn't like the fact that the token is invoked with different redirect_uri as the authorize.
