### ISSUE TITLE
The error field has moved to result.params.error on the latest keycloak version

### ISSUE THREAD

**Issue by eciuca** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#82]
https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/blob/ac3eb39c4d368f711b814d3a4d02045666b276cc/src/app/core/auth.service.ts#L126

**Comment by jeroenheijmans** [comment]
Oh hah, interesting. I noticed that IDS4 also moved things some time ago.

Is there a public KeyCloak server available? I never use it myself. Would be nice to check it against a real server, before we go about changing the example...

Might also be good if someone could dig up the relevant specs, not sure if there is any but would be good to know.

**Comment by jeroenheijmans** [comment]
I've spent a good hour just now but could not find the RFC or OpenID spec where the structure of this object is described. Will leave this issue sit for some more time, if anyone does have some documentation or preferably even official specs on what to expect from the Identity Server side of things: do let us know!

**Comment by jeroenheijmans** [comment]
There haven't been any updates on this specific issue, and I don't have bandwidth to update the sample to the very specifics of each IDS solution, so I'm closing this issue for now. If someone feels like adding some info afterwards anyways that would still be nice to future readers of course!
