### ISSUE TITLE
Login (by navigating to `/login`) when the user opens the page

### ISSUE THREAD

**Issue by SurjitSahoo** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#86]
Hi I want do something similar to #39 . But for login I want to route the user to /login route to display some message there and call the loginSequence from there. But I'm getting stuck at infinite loop between `/login` & `/callback` routes. Can you please help me on this? Thanks.

**Comment by jeroenheijmans** [comment]
Hi @SurjitSahoo sorry to hear you're having problems adapting this sample to your own needs. I'm afraid I don't have bandwidth to support individual implementation scenarios though. I recommend asking a friend, colleague, or paid consultant to help you work through the issues you encounter. Hope you'll understand!
