### ISSUE TITLE
I've AWS Cognito like an IDP but it doens´t work

### ISSUE THREAD

**Issue by OscarJVD** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#97]
![image](https://user-images.githubusercontent.com/57403552/142666926-26949e43-0ef0-42f2-b13f-ed1faa157987.png)
![image](https://user-images.githubusercontent.com/57403552/142666946-a0a05025-81cc-41a1-9c27-2b2bf0070d6f.png)
I've AWS Cognito like an IDP but it doens´t work

**Comment by jeroenheijmans** [comment]
I'm sorry to hear you're having problems, but it's a tad impolite to post an issue to an open source sample repo like that, even without nearly any details at all, and hardly related to the sample itself. I recommend asking a friend, colleague, or paid consultant for help.
