### ISSUE TITLE
Auth service unit test is incorrect

### ISSUE THREAD

**Issue by ThibaultBarco** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#98]
How to reproduce:
- run ```npm run test```
- all tests succeed as expected
- modify expects for test on line 62 in auth.service.spec.ts (same issue applies for 73 and 88)
```
it('should login via hash if token is valid', waitForAsync (() => {
      spyOn(mockService, 'tryLogin');
      spyOn(mockService, 'silentRefresh');
      mockService.updateTokenValidity(true);

      service.runInitialLoginSequence().then(() => {
        expect(mockService.tryLogin).toHaveBeenCalled();
        expect(mockService.silentRefresh).not.toHaveBeenCalled();
      });
```
to
```
it('should login via hash if token is valid', waitForAsync (() => {
      spyOn(mockService, 'tryLogin');
      spyOn(mockService, 'silentRefresh');
      mockService.updateTokenValidity(true);

      service.runInitialLoginSequence().then(() => {
        expect(mockService.tryLogin).not.toHaveBeenCalled();
        expect(mockService.silentRefresh).toHaveBeenCalled();
      });
```
- run ```npm run test``` again
- test still succeeds which shouldn't happen

**Comment by jeroenheijmans** [comment]
Thanks for catching this!

I wish there was some easy way to make Jasmine fail specs without assertions, instead of only warning about it.

Regardless, the test needs to be fixed an made less fragile, will have a look (and also open to suggestions).

**Comment by ThibaultBarco** [comment]
I think a found the issue in the mock.ts file
```
 loadDiscoveryDocument(fullUrl?: string): Promise<OAuthSuccessEvent> {
    return new Promise((_) => { });
  }
```
needs to be
```
  loadDiscoveryDocument(fullUrl?: string): Promise<OAuthSuccessEvent> {
    return Promise.resolve({} as OAuthSuccessEvent);
  }
 ```
 This fixes the assertions in my own application, I guess that some of the other mocked functions would also need this in order to work properly

**Comment by jeroenheijmans** [comment]
Thanks again for catching this! Should be fixed now, and in the future having no assertions will fail tests in general. See also #100 for more coverage some time in the future.
